### ISSUE TITLE
Synapse system dacpac missing extended procedures

### ISSUE THREAD

**Issue by jbtcode** [microsoft/DacFx#212]
- MSSQL Extension Version: 1.16.0
- VSCode Version: 1.74.2
- OS Version: Windows 10 Enterprise 

How to reference system stored procedure like `sp_executesql` ?

I'm getting this warning for my stored procedure which uses `sp_executesql` :
```
Build warning SQL71502: SqlProcedure: [meta].[usp_test] contains an unresolved reference to an object. Either the object does not exist or the reference is ambiguous because it could refer to any of the following objects: [dbo].[sp_executesql] or [meta].[sp_executesql].
```

I added a reference to the master database but that doesn't solve the warning, the project file looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.3-preview" />
  <PropertyGroup>
    <Name>synapse</Name>
    <ProjectGuid>{8688EAA4-F8D6-4AB6-9122-F4EC5F406D3B}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlDwDatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CS</ModelCollation>
    <DefaultCollation>SQL_Latin1_General_CP1_CS_AS</DefaultCollation>
  </PropertyGroup>
  <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
  <ItemGroup>
    <ArtifactReference Include="./_build/AzureDw_master.dacpac">
      <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
    </ArtifactReference>
  </ItemGroup>
</Project>
```

I tried to reference `sys.sp_executesql` (which actually "works" in synapse dedicated pool), but which the compiler still doesn't like:
```
stdout:  Build warning SQL71502: SqlProcedure: [meta].[usp_test] has an unresolved reference to object [sys].[sp_executesql]. 
```
I found this reference from visual studio 2019 where apparently a bug was solved back in 2020, but it doesn't seem to work for me in vscode mssql extension: https://developercommunity.visualstudio.com/t/Warning-in-VS2019-:-object-does-not-exis/824096.

That same page hints that including a "master" dacpac doesn't actually work for synapse all together.

**Comment by kisantia** [comment]
transferred this issue to the DacFx repo because this isn't ADS sql projects specific

**Comment by brain246** [comment]
> Ok got it. Can you try this scenario in SSDT and see if there are any errors there? The sql projects extension in ADS and SSDT should be using the same master dacpacs, but it's possible the one in ADS needs to be updated.

I can help out here: I am getting the same warnings in SSDT for sp_executesql. Database reference for master db is contained in the project. It also doesn't matter if i write dbo.sp_executesql or sys.sp_executesl (that was how i used it in SQL Server usually).

```
Warning	SQL71502: Procedure: [dbo].[create_table_definition] has an unresolved reference to object [sys].[sp_executesql].	[...] 89 IntelliSense.
Severity	Code	Description	Project	Path	File	Line	Source	Suppression State
Warning	SQL71502: Procedure: [dbo].[prc_sqldw_create_stats] has an unresolved reference to object [dbo].[sp_executesql].	[...] 76 IntelliSense	.
```

But it's _just a warning_. Build process works nonetheless.

**Comment by rohkhann** [comment]
Any update on this issue, im having the same issue.

**Comment by ErikEJ** [comment]
@jmetzach Other nuget packages!

**Comment by jbtcode** [comment]
Unfortunaly, after reading up and trying it out, it's still not working.

I added the packagereference using the below entry:

`dotnet add package Microsoft.SqlServer.Dacpacs.Synapse --version 130.0.0`


The project file now looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.9-preview" />
  <PropertyGroup>
    <Name>synapse</Name>
    <ProjectGuid>{8688EAA4-F8D6-4AB6-9122-F4EC5F406D3B}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlDwDatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CS</ModelCollation>
    <DefaultCollation>SQL_Latin1_General_CP1_CS_AS</DefaultCollation>
  </PropertyGroup>
  <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.Dacpacs.Synapse" Version="130.0.0" />
  </ItemGroup>  
</Project>
```

But I'm still getting the same warnings. I know they're only warnings, but I have many such cases so it _is_ a problem for us because it's hard to distinguish from other warnings which I want to know about (and stop the build for)

Example warning when using `sys.sp_executesql` syntax:
```
C:\src\synapse\synapsedb\stored_procedures\meta.usp_merge_to_ods.sql(533,10,533,10): Build warning 
 SQL71502: SqlProcedure: [meta].[usp_merge_to_ods] has an unresolved reference to object [sys].[sp_executesql]. [C:\src\synapse\synapsedb\synapsedb.sqlproj]
```
Example warning when omittingthe schema (which is perfectly fine as well):

```
C:\src\synapse\synapsedb\stored_procedures\meta.usp_delete_landing_data.sql(34,7,34,7): Build warn 
ing SQL71562: SqlProcedure: [meta].[usp_delete_landing_data] has an unresolved reference to object [master].[sys].[sp_executesql]. [C:\src\synapse\synapsedb\synapsedb.sqlproj]
```

**Comment by zijchen** [comment]
@jbtcode I took a look at the master.dacpac for Synapse and noticed it's missing some elements. It's actually missing all of the extended procedures including `sp_executesql`. We'll work on getting those added correctly.

**Comment by zijchen** [comment]
We have released a new Nuget package containing the latest master.dacpac, give this a try: https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Synapse.Master

**Comment by ErikEJ** [comment]
Does the docs need an Update?

**Comment by zijchen** [comment]
Yes we'll update the docs shortly.

**Comment by jbtcode** [comment]
Hi, this solved part of the problem, the references to `sp_executesql` and other procedures are now working.

However, the dacpac in this nupkg is still missing quite some objects, which did exist in the previous dacpac (the one I found in https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs.Master)  

For example the systems views (which I need to use to query the synapse request executions information) are missing:

* `dm_pdw_request_steps` and
* `dm_pdw_request_steps`

... but those are far from the only ones, the "old" dacpac is about four times the size of the new one.

I thought, maybe the idea is to use both, but then that could cause conflicts as well I presume?
