### ISSUE TITLE
MSB4011 building with 2.0.0-preview.1

### ISSUE THREAD

**Issue by avivanoff** [microsoft/DacFx#623]
**Steps to Reproduce:**

1. Create a simple project targeting Microsoft.Sql.Build 2.0.0-preview.1 ([attached](https://github.com/user-attachments/files/19952816/Database.zip)).
2. Build the project.

**Did this occur in prior versions?  If not - which version(s) did it work in?**
No working in 1.0.0.

(DacFx/SqlPackage/SSMS/Azure Data Studio)

**Comment by justintoth** [comment]
I'm seeing similar on 2.0.0-preview.1, but in my case it's on the Azure build server so no ARM architecture is involved.

> 2025-04-29T12:57:46.9324423Z          Building solution configuration "Release|Any CPU".
> 2025-04-29T12:57:47.5840819Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Application\Application.sqlproj]
> 2025-04-29T12:57:47.5852783Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Application\Application.sqlproj]
> 2025-04-29T12:57:47.5858445Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Application\Application.sqlproj]
> 2025-04-29T12:57:47.5863549Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Application\Application.sqlproj]
> 2025-04-29T12:57:47.5868985Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Application\Application.sqlproj]
> 2025-04-29T12:57:47.5870448Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Application\Application.sqlproj]
> 2025-04-29T12:57:47.6573385Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\StaticData\StaticData.sqlproj]
> 2025-04-29T12:57:47.6576957Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\StaticData\StaticData.sqlproj]
> 2025-04-29T12:57:47.6585578Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\StaticData\StaticData.sqlproj]
> 2025-04-29T12:57:47.6643644Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\StaticData\StaticData.sqlproj]
> 2025-04-29T12:57:47.6652437Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Logging\Logging.sqlproj]
> 2025-04-29T12:57:47.6660060Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\StaticData\StaticData.sqlproj]
> 2025-04-29T12:57:47.6664359Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\StaticData\StaticData.sqlproj]
> 2025-04-29T12:57:47.6666176Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Logging\Logging.sqlproj]
> 2025-04-29T12:57:47.6671432Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Logging\Logging.sqlproj]
> 2025-04-29T12:57:47.6674175Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Logging\Logging.sqlproj]
> 2025-04-29T12:57:47.6683345Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Logging\Logging.sqlproj]
> 2025-04-29T12:57:47.6688208Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Logging\Logging.sqlproj]
> 2025-04-29T12:57:47.6697700Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Testing\Testing.sqlproj]
> 2025-04-29T12:57:47.6707441Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Cache\Cache.sqlproj]
> 2025-04-29T12:57:47.6711239Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Cache\Cache.sqlproj]
> 2025-04-29T12:57:47.6716258Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Cache\Cache.sqlproj]
> 2025-04-29T12:57:47.6719011Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Cache\Cache.sqlproj]
> 2025-04-29T12:57:47.6721308Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Testing\Testing.sqlproj]
> 2025-04-29T12:57:47.6726671Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Testing\Testing.sqlproj]
> 2025-04-29T12:57:47.6729492Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Testing\Testing.sqlproj]
> 2025-04-29T12:57:47.6734666Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Cache\Cache.sqlproj]
> 2025-04-29T12:57:47.6740320Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Testing\Testing.sqlproj]
> 2025-04-29T12:57:47.6742931Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Cache\Cache.sqlproj]
> 2025-04-29T12:57:47.6745025Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\Testing\Testing.sqlproj]
> 2025-04-29T12:57:47.6752622Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\OrgManagement\OrgManagement.sqlproj]
> 2025-04-29T12:57:47.6756371Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\OrgManagement\OrgManagement.sqlproj]
> 2025-04-29T12:57:47.6762507Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\OrgManagement\OrgManagement.sqlproj]
> 2025-04-29T12:57:47.6765150Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\OrgManagement\OrgManagement.sqlproj]
> 2025-04-29T12:57:47.6769777Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\OrgManagement\OrgManagement.sqlproj]
> 2025-04-29T12:57:47.6772973Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\OrgManagement\OrgManagement.sqlproj]
> 2025-04-29T12:57:47.6923612Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\SearchCache\SearchCache.sqlproj]
> 2025-04-29T12:57:47.6928496Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(32,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (10,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\SearchCache\SearchCache.sqlproj]
> 2025-04-29T12:57:47.6935159Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\SearchCache\SearchCache.sqlproj]
> 2025-04-29T12:57:47.6938495Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.CurrentVersion.targets(347,5): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.targets" cannot be imported again. It was already imported at "C:\Program Files\dotnet\sdk\9.0.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (38,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\SearchCache\SearchCache.sqlproj]
> 2025-04-29T12:57:47.6945350Z ##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): Warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\SearchCache\SearchCache.sqlproj]
> 2025-04-29T12:57:47.6948373Z      0>C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.CSharp.targets(36,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Managed.targets (18,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\agent1\_work\5\s\Databases\SearchCache\SearchCache.sqlproj]

**Comment by zijchen** [comment]
This warning only occurs in msbuild and should be fixed in the next Visual Studio release

**Comment by zijchen** [comment]
> [@zijchen](https://github.com/zijchen), do you mean Visual Studio 2022 17.14?

The change was shipped with DacFx 170 which is not in 17.14. We'll update this thread when we know the version of VS with this change.

**Comment by czb182** [comment]
> > [@zijchen](https://github.com/zijchen), do you mean Visual Studio 2022 17.14?
> 
> The change was shipped with DacFx 170 which is not in 17.14. We'll update this thread when we know the version of VS with this change.

17.14 is still in preview, can you see if they can include. These VS releases are months apart.

**Comment by avivanoff** [comment]
@zijchen, Visual Studio 2022 17.14 was released, the issue still present.
